version: "3.4"

services:
  desafio-pontotel-backend:
    container_name: desafio-pontotel-backend
    image: desafio-pontotel-backend
    environment:
      - PORT=5000
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: Dockerfile